extends CanvasLayer
## The chiseled-stone update notice the player sees on launch.
##
## The whole UI is built in code so this is a single drop-in file with no
## .tscn to keep in sync, and so the palette below can stay identical to
## the website's.
##
## SETUP
##   1. Autoload this after UpdateChecker, named `UpdatePanel`.
##   2. From your main menu:
##          UpdateChecker.update_available.connect(UpdatePanel.show_update)
##          UpdateChecker.check_for_update()
##
## Nothing else is required — the panel wires itself to the checker's
## download signals when it opens.

# --- palette: these are the site's tokens, verbatim ------------------
const STONE_DEEP   := Color("191715")
const STONE_PANEL  := Color("2b2724")
const STONE_RAISED := Color("383330")
const STONE_EDGE   := Color("5d554c")
const GOLD         := Color("d4a94a")
const GOLD_BRIGHT  := Color("f4dfa2")
const GOLD_DEEP    := Color("7d5a1c")
const TEXT         := Color("ece3d2")
const TEXT_MUTED   := Color("a89c8a")

## Optional. Generated by `npm run qr` in the portfolio repo.
const QR_PATH := "res://assets/update_qr.png"

var _info: Dictionary = {}

var _dimmer: ColorRect
var _title: Label
var _subtitle: Label
var _notes: RichTextLabel
var _status: Label
var _bar: ProgressBar
var _primary: Button
var _secondary: Button
var _dismiss: Button
var _link: Label
var _qr: TextureRect


func _ready() -> void:
	layer = 128
	_build()
	hide_panel()


# ---------------------------------------------------------------------
# Public
# ---------------------------------------------------------------------

func show_update(info: Dictionary) -> void:
	_info = info

	_title.text = "A NEW SEAM HAS OPENED"
	_subtitle.text = "Version %s is ready.  You are running %s." % [
		info.get("version", "?"), UpdateChecker.current_version
	]

	var lines: Array = info.get("notes", [])
	_notes.clear()
	if lines.is_empty():
		_notes.push_color(TEXT_MUTED)
		_notes.add_text("No notes were carved for this release.")
		_notes.pop()
	else:
		for line in lines:
			_notes.push_color(GOLD_DEEP)
			_notes.add_text("◆  ")
			_notes.pop()
			_notes.push_color(TEXT_MUTED)
			_notes.add_text(str(line) + "\n")
			_notes.pop()

	_bar.visible = false
	_status.text = ""
	_link.text = UpdateChecker.PAGE_URL

	# A handheld build cannot replace itself, so it gets the link route.
	if UpdateChecker.can_self_install() and not info.get("build", {}).is_empty():
		_primary.text = "DOWNLOAD  &  INSTALL"
		_primary.disabled = false
	else:
		_primary.text = "OPEN  DOWNLOAD  PAGE"
		_primary.disabled = false

	# A mandatory update can be postponed, but we do not pretend
	# otherwise — the player is told, not trapped.
	_dismiss.text = "LATER" if not info.get("mandatory", false) else "SKIP FOR NOW"

	visible = true
	_primary.grab_focus()


func hide_panel() -> void:
	visible = false


# ---------------------------------------------------------------------
# Actions
# ---------------------------------------------------------------------

func _on_primary() -> void:
	if not UpdateChecker.can_self_install() or _info.get("build", {}).is_empty():
		UpdateChecker.open_download_page()
		return

	_primary.disabled = true
	_secondary.disabled = true
	_bar.visible = true
	_bar.value = 0
	_status.text = "Hauling it up the shaft…"

	UpdateChecker.download_progress.connect(_on_progress)
	UpdateChecker.download_failed.connect(_on_failed, CONNECT_ONE_SHOT)
	UpdateChecker.ready_to_install.connect(_on_ready, CONNECT_ONE_SHOT)
	UpdateChecker.download_update()


func _on_progress(received: int, total: int) -> void:
	if total <= 0:
		_status.text = "Hauling it up the shaft…  %.1f MB" % (received / 1048576.0)
		return
	_bar.value = float(received) / float(total) * 100.0
	_status.text = "Hauling it up the shaft…  %.1f / %.1f MB" % [
		received / 1048576.0, total / 1048576.0
	]


func _on_ready(_path: String) -> void:
	_disconnect_progress()
	_bar.value = 100
	_status.text = "Seal verified. Closing to install…"
	await get_tree().create_timer(1.2).timeout
	UpdateChecker.install_and_restart()


func _on_failed(reason: String) -> void:
	_disconnect_progress()
	_bar.visible = false
	_status.text = reason + "  Use the link below instead."
	_primary.text = "OPEN  DOWNLOAD  PAGE"
	_primary.disabled = false
	_secondary.disabled = false
	_info["build"] = {}  # force the link route from here on


func _disconnect_progress() -> void:
	if UpdateChecker.download_progress.is_connected(_on_progress):
		UpdateChecker.download_progress.disconnect(_on_progress)


func _on_copy() -> void:
	UpdateChecker.copy_link()
	_secondary.text = "LINK  COPIED"
	await get_tree().create_timer(1.5).timeout
	_secondary.text = "COPY  LINK"


# ---------------------------------------------------------------------
# Construction
# ---------------------------------------------------------------------

func _build() -> void:
	# --- dimmer -------------------------------------------------------
	_dimmer = ColorRect.new()
	_dimmer.color = Color(0, 0, 0, 0.72)
	_dimmer.set_anchors_preset(Control.PRESET_FULL_RECT)
	_dimmer.mouse_filter = Control.MOUSE_FILTER_STOP
	add_child(_dimmer)

	# --- centring -----------------------------------------------------
	var center := CenterContainer.new()
	center.set_anchors_preset(Control.PRESET_FULL_RECT)
	center.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(center)

	# --- the slab -----------------------------------------------------
	var slab := PanelContainer.new()
	slab.custom_minimum_size = Vector2(620, 0)
	slab.add_theme_stylebox_override("panel", _stone_slab())
	center.add_child(slab)

	var col := VBoxContainer.new()
	col.add_theme_constant_override("separation", 14)
	slab.add_child(col)

	# --- heading ------------------------------------------------------
	_title = Label.new()
	_title.add_theme_font_size_override("font_size", 26)
	_title.add_theme_color_override("font_color", TEXT)
	_title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	col.add_child(_title)

	col.add_child(_gold_rule())

	_subtitle = Label.new()
	_subtitle.add_theme_font_size_override("font_size", 14)
	_subtitle.add_theme_color_override("font_color", GOLD)
	_subtitle.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	col.add_child(_subtitle)

	# --- notes, sunk into the face of the slab ------------------------
	var well := PanelContainer.new()
	well.add_theme_stylebox_override("panel", _sunken_well())
	well.size_flags_vertical = Control.SIZE_EXPAND_FILL
	col.add_child(well)

	_notes = RichTextLabel.new()
	_notes.bbcode_enabled = true
	_notes.fit_content = true
	_notes.custom_minimum_size = Vector2(0, 150)
	_notes.scroll_active = true
	_notes.add_theme_font_size_override("normal_font_size", 14)
	well.add_child(_notes)

	# --- progress -----------------------------------------------------
	_bar = ProgressBar.new()
	_bar.custom_minimum_size = Vector2(0, 14)
	_bar.show_percentage = false
	_bar.add_theme_stylebox_override("background", _sunken_well())
	_bar.add_theme_stylebox_override("fill", _gold_fill())
	col.add_child(_bar)

	_status = Label.new()
	_status.add_theme_font_size_override("font_size", 13)
	_status.add_theme_color_override("font_color", TEXT_MUTED)
	_status.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	_status.autowrap_mode = TextServer.AUTOWRAP_WORD_SMART
	col.add_child(_status)

	# --- buttons ------------------------------------------------------
	var row := HBoxContainer.new()
	row.alignment = BoxContainer.ALIGNMENT_CENTER
	row.add_theme_constant_override("separation", 10)
	col.add_child(row)

	_primary = _make_button("DOWNLOAD  &  INSTALL", true)
	_primary.pressed.connect(_on_primary)
	row.add_child(_primary)

	_secondary = _make_button("COPY  LINK", false)
	_secondary.pressed.connect(_on_copy)
	row.add_child(_secondary)

	_dismiss = _make_button("LATER", false)
	_dismiss.pressed.connect(hide_panel)
	row.add_child(_dismiss)

	# --- the address, always visible as the fallback ------------------
	# A handheld has no clipboard worth the name and no browser, so the
	# QR is the only practical way off the device. Generate it with
	# `npm run qr` in the portfolio repo and drop the PNG in as
	# res://assets/update_qr.png; the panel works without it.
	var tail := HBoxContainer.new()
	tail.alignment = BoxContainer.ALIGNMENT_CENTER
	tail.add_theme_constant_override("separation", 14)
	col.add_child(tail)

	if ResourceLoader.exists(QR_PATH):
		_qr = TextureRect.new()
		_qr.texture = load(QR_PATH)
		_qr.custom_minimum_size = Vector2(104, 104)
		_qr.expand_mode = TextureRect.EXPAND_IGNORE_SIZE
		_qr.stretch_mode = TextureRect.STRETCH_KEEP_ASPECT_CENTERED
		tail.add_child(_qr)

	_link = Label.new()
	_link.add_theme_font_size_override("font_size", 12)
	_link.add_theme_color_override("font_color", GOLD_DEEP)
	_link.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	tail.add_child(_link)


func _make_button(text: String, primary: bool) -> Button:
	var b := Button.new()
	b.text = text
	b.custom_minimum_size = Vector2(0, 42)
	b.add_theme_font_size_override("font_size", 13)

	if primary:
		b.add_theme_color_override("font_color", Color("2a1e08"))
		b.add_theme_color_override("font_hover_color", Color("2a1e08"))
		b.add_theme_color_override("font_pressed_color", Color("2a1e08"))
		b.add_theme_stylebox_override("normal", _metal_box(GOLD, GOLD_DEEP))
		b.add_theme_stylebox_override("hover", _metal_box(GOLD_BRIGHT, GOLD))
		b.add_theme_stylebox_override("pressed", _metal_box(GOLD_DEEP, GOLD_DEEP))
		b.add_theme_stylebox_override("disabled", _metal_box(GOLD_DEEP.darkened(0.3), GOLD_DEEP))
	else:
		b.add_theme_color_override("font_color", TEXT)
		b.add_theme_color_override("font_hover_color", GOLD_BRIGHT)
		b.add_theme_stylebox_override("normal", _metal_box(STONE_RAISED, STONE_DEEP))
		b.add_theme_stylebox_override("hover", _metal_box(STONE_EDGE, STONE_DEEP))
		b.add_theme_stylebox_override("pressed", _metal_box(STONE_DEEP, STONE_DEEP))
		b.add_theme_stylebox_override("disabled", _metal_box(STONE_PANEL, STONE_DEEP))

	return b


## The dressed granite face, with a gold band around it.
func _stone_slab() -> StyleBoxFlat:
	var sb := StyleBoxFlat.new()
	sb.bg_color = STONE_PANEL
	sb.set_border_width_all(2)
	sb.border_color = GOLD_DEEP
	sb.set_corner_radius_all(2)
	sb.content_margin_left = 34
	sb.content_margin_right = 34
	sb.content_margin_top = 28
	sb.content_margin_bottom = 26
	sb.shadow_color = Color(0, 0, 0, 0.75)
	sb.shadow_size = 24
	return sb


## A recess cut into the slab.
func _sunken_well() -> StyleBoxFlat:
	var sb := StyleBoxFlat.new()
	sb.bg_color = Color("211e1b")
	sb.set_border_width_all(1)
	sb.border_color = Color("14120f")
	sb.set_corner_radius_all(2)
	sb.set_content_margin_all(14)
	return sb


func _gold_fill() -> StyleBoxFlat:
	var sb := StyleBoxFlat.new()
	sb.bg_color = GOLD
	sb.set_corner_radius_all(1)
	return sb


func _metal_box(face: Color, edge: Color) -> StyleBoxFlat:
	var sb := StyleBoxFlat.new()
	sb.bg_color = face
	sb.border_color = edge
	sb.set_border_width_all(1)
	sb.border_width_bottom = 3
	sb.set_corner_radius_all(2)
	sb.content_margin_left = 20
	sb.content_margin_right = 20
	return sb


## A thin gold inlay, the same motif as the site's rules.
func _gold_rule() -> Control:
	var wrap := CenterContainer.new()
	var rule := ColorRect.new()
	rule.color = GOLD_DEEP
	rule.custom_minimum_size = Vector2(340, 2)
	wrap.add_child(rule)
	return wrap
